name: Film API CD

on: [push]

jobs:
  tests:
    services:
      postgres:
        image: postgres:9.6
        env:
          POSTGRES_NAME: postgres
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
        ports:
          - 5432:5432

    runs-on: ubuntu-latest
    env:
      DJANGO_SETTINGS_MODULE: netflix.settings
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v3
        with:
          python-version: 3.9
      - name: linting
        uses: programmingwithalex/pylinters@v1.4.2
        with:
          python-root: '.'
          flake8-flags: ''
          mypy-flags: '--ignore-missing-imports'
          fail-on-isort: false
          skip-flake8: true
      - name: Install Requirements
        run: pip install -r requirements.txt
      - name: Run tests
        run: |
          flake8
          python -m pytest

  deploy:
    runs-on: ubuntu-latest
    needs: tests
    steps:
      - name: multiple command
        uses: appleboy/ssh-action@master
        with:
          host: 127.0.0.1
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          script: |
            git pull
            systemctl restart gunicorn.service

