name: Film API CD

on: [push]

jobs:
  test:
    services:
      postgres:
        image: postgres:9.6
        env:
          POSTGRES_NAME: postgres
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
        ports:
          - 5432:5432

    runs-on: ubuntu-latest
    env:
      DJANGO_SETTINGS_MODULE: netflix.settings
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v3
        with:
          python-version: 3.9
      - name: Install Requirements
        run: pip install -r requirements.txt

  deploy:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: multiple command
        uses: appleboy/ssh-action@cd
        with:
          host: 127.0.0.1
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          script: |
            git pull
            systemctl restart gunicorn.service

